apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service-sample.fullname" . }}
  labels:
    app: {{ template "service-sample.name" . }}
    chart: {{ template "service-sample.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "service-sample.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "service-sample.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            
            
          
