apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  selector:
    matchLabels:
      app: aspnetapp
      
   template:
    metadata:
      labels:
        app: aspnetapp
        
    spec:
      containers:
        - name: aspnetapp-image
          image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
          ports:
            - containerPort: 80
              protocol: TCP
