apiVersion: v1
kind: Service
metadata:
  name: {{ template "service-sample.fullname" . }}
  labels:
    app: {{ template "service-sample.name" . }}
    solution: {{ .Values.solution }}
    chart: {{ template "service-sample.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 50051
      targetPort: grpc
      name: grpc
    - port: 8081
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "service-sample.name" . }}
    release: {{ .Release.Name }}
